// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: fs.proto

#include "fs.pb.h"
#include "fs.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* FSMasterService_method_names[] = {
  "/FSMasterService/Mount",
  "/FSMasterService/UnMount",
  "/FSMasterService/Open",
  "/FSMasterService/Close",
  "/FSMasterService/Read",
  "/FSMasterService/Write",
  "/FSMasterService/DeleteFile",
  "/FSMasterService/Mkdir",
  "/FSMasterService/Rmdir",
  "/FSMasterService/Ls",
};

std::unique_ptr< FSMasterService::Stub> FSMasterService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FSMasterService::Stub> stub(new FSMasterService::Stub(channel, options));
  return stub;
}

FSMasterService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Mount_(FSMasterService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UnMount_(FSMasterService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Open_(FSMasterService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Close_(FSMasterService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Read_(FSMasterService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Write_(FSMasterService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteFile_(FSMasterService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Mkdir_(FSMasterService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Rmdir_(FSMasterService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Ls_(FSMasterService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FSMasterService::Stub::Mount(::grpc::ClientContext* context, const ::MountRequest& request, ::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::MountRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Mount_, context, request, response);
}

void FSMasterService::Stub::async::Mount(::grpc::ClientContext* context, const ::MountRequest* request, ::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::MountRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Mount_, context, request, response, std::move(f));
}

void FSMasterService::Stub::async::Mount(::grpc::ClientContext* context, const ::MountRequest* request, ::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Mount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::StatusResponse>* FSMasterService::Stub::PrepareAsyncMountRaw(::grpc::ClientContext* context, const ::MountRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::StatusResponse, ::MountRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Mount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::StatusResponse>* FSMasterService::Stub::AsyncMountRaw(::grpc::ClientContext* context, const ::MountRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FSMasterService::Stub::UnMount(::grpc::ClientContext* context, const ::MountRequest& request, ::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::MountRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UnMount_, context, request, response);
}

void FSMasterService::Stub::async::UnMount(::grpc::ClientContext* context, const ::MountRequest* request, ::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::MountRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnMount_, context, request, response, std::move(f));
}

void FSMasterService::Stub::async::UnMount(::grpc::ClientContext* context, const ::MountRequest* request, ::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnMount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::StatusResponse>* FSMasterService::Stub::PrepareAsyncUnMountRaw(::grpc::ClientContext* context, const ::MountRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::StatusResponse, ::MountRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UnMount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::StatusResponse>* FSMasterService::Stub::AsyncUnMountRaw(::grpc::ClientContext* context, const ::MountRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUnMountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FSMasterService::Stub::Open(::grpc::ClientContext* context, const ::OpenRequest& request, ::OpenResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::OpenRequest, ::OpenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Open_, context, request, response);
}

void FSMasterService::Stub::async::Open(::grpc::ClientContext* context, const ::OpenRequest* request, ::OpenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::OpenRequest, ::OpenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Open_, context, request, response, std::move(f));
}

void FSMasterService::Stub::async::Open(::grpc::ClientContext* context, const ::OpenRequest* request, ::OpenResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Open_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::OpenResponse>* FSMasterService::Stub::PrepareAsyncOpenRaw(::grpc::ClientContext* context, const ::OpenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::OpenResponse, ::OpenRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Open_, context, request);
}

::grpc::ClientAsyncResponseReader< ::OpenResponse>* FSMasterService::Stub::AsyncOpenRaw(::grpc::ClientContext* context, const ::OpenRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncOpenRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FSMasterService::Stub::Close(::grpc::ClientContext* context, const ::CloseRequest& request, ::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::CloseRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Close_, context, request, response);
}

void FSMasterService::Stub::async::Close(::grpc::ClientContext* context, const ::CloseRequest* request, ::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::CloseRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Close_, context, request, response, std::move(f));
}

void FSMasterService::Stub::async::Close(::grpc::ClientContext* context, const ::CloseRequest* request, ::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Close_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::StatusResponse>* FSMasterService::Stub::PrepareAsyncCloseRaw(::grpc::ClientContext* context, const ::CloseRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::StatusResponse, ::CloseRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Close_, context, request);
}

::grpc::ClientAsyncResponseReader< ::StatusResponse>* FSMasterService::Stub::AsyncCloseRaw(::grpc::ClientContext* context, const ::CloseRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCloseRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FSMasterService::Stub::Read(::grpc::ClientContext* context, const ::ReadRequest& request, ::ReadResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ReadRequest, ::ReadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Read_, context, request, response);
}

void FSMasterService::Stub::async::Read(::grpc::ClientContext* context, const ::ReadRequest* request, ::ReadResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ReadRequest, ::ReadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Read_, context, request, response, std::move(f));
}

void FSMasterService::Stub::async::Read(::grpc::ClientContext* context, const ::ReadRequest* request, ::ReadResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Read_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ReadResponse>* FSMasterService::Stub::PrepareAsyncReadRaw(::grpc::ClientContext* context, const ::ReadRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ReadResponse, ::ReadRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Read_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ReadResponse>* FSMasterService::Stub::AsyncReadRaw(::grpc::ClientContext* context, const ::ReadRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FSMasterService::Stub::Write(::grpc::ClientContext* context, const ::WriteRequest& request, ::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::WriteRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Write_, context, request, response);
}

void FSMasterService::Stub::async::Write(::grpc::ClientContext* context, const ::WriteRequest* request, ::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::WriteRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Write_, context, request, response, std::move(f));
}

void FSMasterService::Stub::async::Write(::grpc::ClientContext* context, const ::WriteRequest* request, ::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Write_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::StatusResponse>* FSMasterService::Stub::PrepareAsyncWriteRaw(::grpc::ClientContext* context, const ::WriteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::StatusResponse, ::WriteRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Write_, context, request);
}

::grpc::ClientAsyncResponseReader< ::StatusResponse>* FSMasterService::Stub::AsyncWriteRaw(::grpc::ClientContext* context, const ::WriteRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncWriteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FSMasterService::Stub::DeleteFile(::grpc::ClientContext* context, const ::DeleteFileRequest& request, ::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::DeleteFileRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteFile_, context, request, response);
}

void FSMasterService::Stub::async::DeleteFile(::grpc::ClientContext* context, const ::DeleteFileRequest* request, ::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::DeleteFileRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteFile_, context, request, response, std::move(f));
}

void FSMasterService::Stub::async::DeleteFile(::grpc::ClientContext* context, const ::DeleteFileRequest* request, ::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::StatusResponse>* FSMasterService::Stub::PrepareAsyncDeleteFileRaw(::grpc::ClientContext* context, const ::DeleteFileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::StatusResponse, ::DeleteFileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::StatusResponse>* FSMasterService::Stub::AsyncDeleteFileRaw(::grpc::ClientContext* context, const ::DeleteFileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FSMasterService::Stub::Mkdir(::grpc::ClientContext* context, const ::MkdirRequest& request, ::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::MkdirRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Mkdir_, context, request, response);
}

void FSMasterService::Stub::async::Mkdir(::grpc::ClientContext* context, const ::MkdirRequest* request, ::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::MkdirRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Mkdir_, context, request, response, std::move(f));
}

void FSMasterService::Stub::async::Mkdir(::grpc::ClientContext* context, const ::MkdirRequest* request, ::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Mkdir_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::StatusResponse>* FSMasterService::Stub::PrepareAsyncMkdirRaw(::grpc::ClientContext* context, const ::MkdirRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::StatusResponse, ::MkdirRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Mkdir_, context, request);
}

::grpc::ClientAsyncResponseReader< ::StatusResponse>* FSMasterService::Stub::AsyncMkdirRaw(::grpc::ClientContext* context, const ::MkdirRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMkdirRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FSMasterService::Stub::Rmdir(::grpc::ClientContext* context, const ::RmdirRequest& request, ::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::RmdirRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Rmdir_, context, request, response);
}

void FSMasterService::Stub::async::Rmdir(::grpc::ClientContext* context, const ::RmdirRequest* request, ::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::RmdirRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Rmdir_, context, request, response, std::move(f));
}

void FSMasterService::Stub::async::Rmdir(::grpc::ClientContext* context, const ::RmdirRequest* request, ::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Rmdir_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::StatusResponse>* FSMasterService::Stub::PrepareAsyncRmdirRaw(::grpc::ClientContext* context, const ::RmdirRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::StatusResponse, ::RmdirRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Rmdir_, context, request);
}

::grpc::ClientAsyncResponseReader< ::StatusResponse>* FSMasterService::Stub::AsyncRmdirRaw(::grpc::ClientContext* context, const ::RmdirRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRmdirRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FSMasterService::Stub::Ls(::grpc::ClientContext* context, const ::LsRequest& request, ::LsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::LsRequest, ::LsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Ls_, context, request, response);
}

void FSMasterService::Stub::async::Ls(::grpc::ClientContext* context, const ::LsRequest* request, ::LsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::LsRequest, ::LsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ls_, context, request, response, std::move(f));
}

void FSMasterService::Stub::async::Ls(::grpc::ClientContext* context, const ::LsRequest* request, ::LsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ls_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::LsResponse>* FSMasterService::Stub::PrepareAsyncLsRaw(::grpc::ClientContext* context, const ::LsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::LsResponse, ::LsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Ls_, context, request);
}

::grpc::ClientAsyncResponseReader< ::LsResponse>* FSMasterService::Stub::AsyncLsRaw(::grpc::ClientContext* context, const ::LsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLsRaw(context, request, cq);
  result->StartCall();
  return result;
}

FSMasterService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FSMasterService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FSMasterService::Service, ::MountRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FSMasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::MountRequest* req,
             ::StatusResponse* resp) {
               return service->Mount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FSMasterService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FSMasterService::Service, ::MountRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FSMasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::MountRequest* req,
             ::StatusResponse* resp) {
               return service->UnMount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FSMasterService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FSMasterService::Service, ::OpenRequest, ::OpenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FSMasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::OpenRequest* req,
             ::OpenResponse* resp) {
               return service->Open(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FSMasterService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FSMasterService::Service, ::CloseRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FSMasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::CloseRequest* req,
             ::StatusResponse* resp) {
               return service->Close(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FSMasterService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FSMasterService::Service, ::ReadRequest, ::ReadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FSMasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ReadRequest* req,
             ::ReadResponse* resp) {
               return service->Read(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FSMasterService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FSMasterService::Service, ::WriteRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FSMasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::WriteRequest* req,
             ::StatusResponse* resp) {
               return service->Write(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FSMasterService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FSMasterService::Service, ::DeleteFileRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FSMasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::DeleteFileRequest* req,
             ::StatusResponse* resp) {
               return service->DeleteFile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FSMasterService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FSMasterService::Service, ::MkdirRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FSMasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::MkdirRequest* req,
             ::StatusResponse* resp) {
               return service->Mkdir(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FSMasterService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FSMasterService::Service, ::RmdirRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FSMasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::RmdirRequest* req,
             ::StatusResponse* resp) {
               return service->Rmdir(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FSMasterService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FSMasterService::Service, ::LsRequest, ::LsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FSMasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::LsRequest* req,
             ::LsResponse* resp) {
               return service->Ls(ctx, req, resp);
             }, this)));
}

FSMasterService::Service::~Service() {
}

::grpc::Status FSMasterService::Service::Mount(::grpc::ServerContext* context, const ::MountRequest* request, ::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FSMasterService::Service::UnMount(::grpc::ServerContext* context, const ::MountRequest* request, ::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FSMasterService::Service::Open(::grpc::ServerContext* context, const ::OpenRequest* request, ::OpenResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FSMasterService::Service::Close(::grpc::ServerContext* context, const ::CloseRequest* request, ::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FSMasterService::Service::Read(::grpc::ServerContext* context, const ::ReadRequest* request, ::ReadResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FSMasterService::Service::Write(::grpc::ServerContext* context, const ::WriteRequest* request, ::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FSMasterService::Service::DeleteFile(::grpc::ServerContext* context, const ::DeleteFileRequest* request, ::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FSMasterService::Service::Mkdir(::grpc::ServerContext* context, const ::MkdirRequest* request, ::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FSMasterService::Service::Rmdir(::grpc::ServerContext* context, const ::RmdirRequest* request, ::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FSMasterService::Service::Ls(::grpc::ServerContext* context, const ::LsRequest* request, ::LsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* FSServerService_method_names[] = {
  "/FSServerService/ReadBlock",
  "/FSServerService/WriteBlock",
  "/FSServerService/DeleteBlock",
  "/FSServerService/GetBlockInfo",
  "/FSServerService/HeartBeat",
};

std::unique_ptr< FSServerService::Stub> FSServerService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FSServerService::Stub> stub(new FSServerService::Stub(channel, options));
  return stub;
}

FSServerService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ReadBlock_(FSServerService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_WriteBlock_(FSServerService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteBlock_(FSServerService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetBlockInfo_(FSServerService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_HeartBeat_(FSServerService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FSServerService::Stub::ReadBlock(::grpc::ClientContext* context, const ::ReadBlockRequest& request, ::ReadBlockResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ReadBlockRequest, ::ReadBlockResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReadBlock_, context, request, response);
}

void FSServerService::Stub::async::ReadBlock(::grpc::ClientContext* context, const ::ReadBlockRequest* request, ::ReadBlockResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ReadBlockRequest, ::ReadBlockResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadBlock_, context, request, response, std::move(f));
}

void FSServerService::Stub::async::ReadBlock(::grpc::ClientContext* context, const ::ReadBlockRequest* request, ::ReadBlockResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadBlock_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ReadBlockResponse>* FSServerService::Stub::PrepareAsyncReadBlockRaw(::grpc::ClientContext* context, const ::ReadBlockRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ReadBlockResponse, ::ReadBlockRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReadBlock_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ReadBlockResponse>* FSServerService::Stub::AsyncReadBlockRaw(::grpc::ClientContext* context, const ::ReadBlockRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadBlockRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FSServerService::Stub::WriteBlock(::grpc::ClientContext* context, const ::WriteBlockRequest& request, ::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::WriteBlockRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_WriteBlock_, context, request, response);
}

void FSServerService::Stub::async::WriteBlock(::grpc::ClientContext* context, const ::WriteBlockRequest* request, ::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::WriteBlockRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WriteBlock_, context, request, response, std::move(f));
}

void FSServerService::Stub::async::WriteBlock(::grpc::ClientContext* context, const ::WriteBlockRequest* request, ::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WriteBlock_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::StatusResponse>* FSServerService::Stub::PrepareAsyncWriteBlockRaw(::grpc::ClientContext* context, const ::WriteBlockRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::StatusResponse, ::WriteBlockRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_WriteBlock_, context, request);
}

::grpc::ClientAsyncResponseReader< ::StatusResponse>* FSServerService::Stub::AsyncWriteBlockRaw(::grpc::ClientContext* context, const ::WriteBlockRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncWriteBlockRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FSServerService::Stub::DeleteBlock(::grpc::ClientContext* context, const ::DeleteBlockRequest& request, ::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::DeleteBlockRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteBlock_, context, request, response);
}

void FSServerService::Stub::async::DeleteBlock(::grpc::ClientContext* context, const ::DeleteBlockRequest* request, ::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::DeleteBlockRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteBlock_, context, request, response, std::move(f));
}

void FSServerService::Stub::async::DeleteBlock(::grpc::ClientContext* context, const ::DeleteBlockRequest* request, ::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteBlock_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::StatusResponse>* FSServerService::Stub::PrepareAsyncDeleteBlockRaw(::grpc::ClientContext* context, const ::DeleteBlockRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::StatusResponse, ::DeleteBlockRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteBlock_, context, request);
}

::grpc::ClientAsyncResponseReader< ::StatusResponse>* FSServerService::Stub::AsyncDeleteBlockRaw(::grpc::ClientContext* context, const ::DeleteBlockRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteBlockRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FSServerService::Stub::GetBlockInfo(::grpc::ClientContext* context, const ::GetBlockInfoRequest& request, ::GetBlockInfoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GetBlockInfoRequest, ::GetBlockInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetBlockInfo_, context, request, response);
}

void FSServerService::Stub::async::GetBlockInfo(::grpc::ClientContext* context, const ::GetBlockInfoRequest* request, ::GetBlockInfoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GetBlockInfoRequest, ::GetBlockInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetBlockInfo_, context, request, response, std::move(f));
}

void FSServerService::Stub::async::GetBlockInfo(::grpc::ClientContext* context, const ::GetBlockInfoRequest* request, ::GetBlockInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetBlockInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GetBlockInfoResponse>* FSServerService::Stub::PrepareAsyncGetBlockInfoRaw(::grpc::ClientContext* context, const ::GetBlockInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GetBlockInfoResponse, ::GetBlockInfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetBlockInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GetBlockInfoResponse>* FSServerService::Stub::AsyncGetBlockInfoRaw(::grpc::ClientContext* context, const ::GetBlockInfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetBlockInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FSServerService::Stub::HeartBeat(::grpc::ClientContext* context, const ::HeartBeatRequest& request, ::HeartBeatResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::HeartBeatRequest, ::HeartBeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HeartBeat_, context, request, response);
}

void FSServerService::Stub::async::HeartBeat(::grpc::ClientContext* context, const ::HeartBeatRequest* request, ::HeartBeatResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::HeartBeatRequest, ::HeartBeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HeartBeat_, context, request, response, std::move(f));
}

void FSServerService::Stub::async::HeartBeat(::grpc::ClientContext* context, const ::HeartBeatRequest* request, ::HeartBeatResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HeartBeat_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::HeartBeatResponse>* FSServerService::Stub::PrepareAsyncHeartBeatRaw(::grpc::ClientContext* context, const ::HeartBeatRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::HeartBeatResponse, ::HeartBeatRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HeartBeat_, context, request);
}

::grpc::ClientAsyncResponseReader< ::HeartBeatResponse>* FSServerService::Stub::AsyncHeartBeatRaw(::grpc::ClientContext* context, const ::HeartBeatRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHeartBeatRaw(context, request, cq);
  result->StartCall();
  return result;
}

FSServerService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FSServerService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FSServerService::Service, ::ReadBlockRequest, ::ReadBlockResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FSServerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ReadBlockRequest* req,
             ::ReadBlockResponse* resp) {
               return service->ReadBlock(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FSServerService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FSServerService::Service, ::WriteBlockRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FSServerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::WriteBlockRequest* req,
             ::StatusResponse* resp) {
               return service->WriteBlock(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FSServerService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FSServerService::Service, ::DeleteBlockRequest, ::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FSServerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::DeleteBlockRequest* req,
             ::StatusResponse* resp) {
               return service->DeleteBlock(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FSServerService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FSServerService::Service, ::GetBlockInfoRequest, ::GetBlockInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FSServerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GetBlockInfoRequest* req,
             ::GetBlockInfoResponse* resp) {
               return service->GetBlockInfo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FSServerService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FSServerService::Service, ::HeartBeatRequest, ::HeartBeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FSServerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::HeartBeatRequest* req,
             ::HeartBeatResponse* resp) {
               return service->HeartBeat(ctx, req, resp);
             }, this)));
}

FSServerService::Service::~Service() {
}

::grpc::Status FSServerService::Service::ReadBlock(::grpc::ServerContext* context, const ::ReadBlockRequest* request, ::ReadBlockResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FSServerService::Service::WriteBlock(::grpc::ServerContext* context, const ::WriteBlockRequest* request, ::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FSServerService::Service::DeleteBlock(::grpc::ServerContext* context, const ::DeleteBlockRequest* request, ::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FSServerService::Service::GetBlockInfo(::grpc::ServerContext* context, const ::GetBlockInfoRequest* request, ::GetBlockInfoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FSServerService::Service::HeartBeat(::grpc::ServerContext* context, const ::HeartBeatRequest* request, ::HeartBeatResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


